/* ========================================
   Data: 60 Cantonese Opera Characters
   (30 male + 30 female), Questions, i18n
   All characters verified from real 粤剧 repertoire.
   See research notes in code comments.
   ======================================== */

window.TRAITS = ['痴情', '烈', '飘逸', '智慧', '谐趣', '决绝'];

/* ========================================
   60 CHARACTERS
   gender: 'male' | 'female'
   role_type: 文武生/小生/武生/净/老生/丑生/正印花旦/二帮花旦/武旦/刀马旦/老旦/彩旦
   ======================================== */

window.CHARACTERS = [

  /* ============================================ */
  /* ===          男角 · MALE (30)            === */
  /* ============================================ */

  /* === 唐涤生四大名剧 男主 === */
  {
    id: 'zhoushixian',
    gender: 'male',
    role_type: '文武生',
    name_cn: '周世显', name_en: 'Zhou Shixian',
    play_cn: '《帝女花》', play_en: 'Princess Changping',
    traits: { '痴情': 9, '烈': 5, '飘逸': 7, '智慧': 8, '谐趣': 1, '决绝': 9 },
    quote_cn: '一缕香魂红线断，长平赴死我同行。',
    quote_en: 'When the red thread of her soul shall break — I follow Changping into death.',
    letter_cn: '你和周世显一样，把"承诺"看得比命还重。在所有人松开手的时候，你紧紧握住——这种重，世界未必懂，但有一个人懂，就够了。',
    letter_en: 'Like Zhou Shixian, you hold a promise heavier than your own life. When others let go, you tighten your grip — the world may not understand, but one person does. That is enough.',
    monologue_cn: '若你问我是否后悔——花开过了，我便不悔。',
    monologue_en: 'You ask if I regret — once the flower has bloomed, I do not.',
    event_cn: '广府大剧院 · 5 月 18 日', event_en: 'Guangfu Grand Theatre · May 18'
  },
  {
    id: 'liyi',
    gender: 'male',
    role_type: '文武生',
    name_cn: '李益', name_en: 'Li Yi',
    play_cn: '《紫钗记》', play_en: 'The Purple Hairpin',
    traits: { '痴情': 7, '烈': 4, '飘逸': 7, '智慧': 8, '谐趣': 2, '决绝': 4 },
    quote_cn: '一钗在手，半生再寻。',
    quote_en: 'A hairpin in hand — half a life spent in the search.',
    letter_cn: '你和李益一样，会在事情过去很久之后才意识到自己有多在乎。世故不能消蚀的，是某些回忆里的清亮。',
    letter_en: 'Like Li Yi, you only realize how much you cared long after the moment has passed. The world dims much — but it cannot dull the brightness of certain memories.',
    monologue_cn: '我赶不及当年的雨——但我赶上了这一夜。',
    monologue_en: 'I could not catch the rain of that year — but I am here for this night.',
    event_cn: '南国剧场 · 6 月 1 日', event_en: 'Nanguo Theatre · June 1'
  },
  {
    id: 'liumengmei',
    gender: 'male',
    role_type: '文武生',
    name_cn: '柳梦梅', name_en: 'Liu Mengmei',
    play_cn: '《牡丹亭惊梦》', play_en: 'The Peony Pavilion',
    traits: { '痴情': 9, '烈': 3, '飘逸': 9, '智慧': 6, '谐趣': 2, '决绝': 6 },
    quote_cn: '梦里相逢花下立，惊回竟是牡丹魂。',
    quote_en: 'In a dream we met beneath the blossoms — and waking, I learned: she was the soul of the peony.',
    letter_cn: '你和柳梦梅一样，会被一段没逻辑的缘分牵走。事情合不合理你都要去做——只要"心"先点过头。',
    letter_en: 'Like Liu Mengmei, you can be drawn away by a connection without reason. Whether things make sense or not, you will go — so long as your heart has already nodded yes.',
    monologue_cn: '我寻你寻得有些远——但你看，我到了。',
    monologue_en: 'I have searched for you a long way — but, see, I have arrived.',
    event_cn: '广府大剧院 · 5 月 30 日', event_en: 'Guangfu Grand Theatre · May 30'
  },
  {
    id: 'peiyu',
    gender: 'male',
    role_type: '文武生',
    name_cn: '裴禹', name_en: 'Pei Yu',
    play_cn: '《再世红梅记》', play_en: 'Reborn from the Red Plum',
    traits: { '痴情': 9, '烈': 4, '飘逸': 8, '智慧': 7, '谐趣': 2, '决绝': 5 },
    quote_cn: '红梅一束寄相思，前世今生不可移。',
    quote_en: 'A bough of red plum sent as longing — neither past life nor this life can move.',
    letter_cn: '你和裴禹一样，是会被一束花、一个眼神、一段没说完的话击中的人。世界粗砺，你偏偏温柔。',
    letter_en: 'Like Pei Yu, you are one who can be struck by a bough of flowers, by a glance, by an unfinished word. The world is rough — and yet you remain soft.',
    monologue_cn: '我等过冬天，也等过两个春天。',
    monologue_en: 'I have waited a winter — and then, two springs.',
    event_cn: '广府大剧院 · 5 月 25 日', event_en: 'Guangfu Grand Theatre · May 25'
  },

  /* === 其他经典爱情剧男主 === */
  {
    id: 'zhaoruzhou',
    gender: 'male',
    role_type: '文武生',
    name_cn: '赵汝州', name_en: 'Zhao Ruzhou',
    play_cn: '《蝶影红梨记》', play_en: 'Butterfly and Red Pear Blossom',
    traits: { '痴情': 8, '烈': 4, '飘逸': 7, '智慧': 8, '谐趣': 3, '决绝': 6 },
    quote_cn: '红梨花下识倾城，蝶影双双不必惊。',
    quote_en: 'Beneath the red pear blossoms I knew her face — let no one startle the paired butterfly-shadows.',
    letter_cn: '你和赵汝州一样，能在一个看似遥远的人身上一眼认出"对的那个"。后来才发现，是命运早就安排好了一场偶遇。',
    letter_en: 'Like Zhao Ruzhou, you can recognize "the right one" in someone who seemed far away. Only later you realize fate had arranged the meeting all along.',
    monologue_cn: '梨花未落，蝶影还在——你来得正好。',
    monologue_en: 'The pear blossoms have not fallen, the butterflies still pair — you have come at the right time.',
    event_cn: '南国剧场 · 6 月 8 日', event_en: 'Nanguo Theatre · June 8'
  },
  {
    id: 'jiangshilong',
    gender: 'male',
    role_type: '文武生',
    name_cn: '蒋世隆', name_en: 'Jiang Shilong',
    play_cn: '《双仙拜月亭》', play_en: 'Two Immortals at the Moon Altar',
    traits: { '痴情': 8, '烈': 5, '飘逸': 6, '智慧': 7, '谐趣': 3, '决绝': 7 },
    quote_cn: '风雨同伞，便是夫妻。',
    quote_en: 'One umbrella in wind and rain — and we were husband and wife.',
    letter_cn: '你和蒋世隆一样，能在最乱的时候做最稳的决定。乱世里你那句"不松手"比和平时期的一千句承诺都重。',
    letter_en: 'Like Jiang Shilong, in the most chaotic moment you can make the steadiest decision. Your "I will not let go" in turbulent times is heavier than a thousand peacetime vows.',
    monologue_cn: '雨没停，伞也没收——你来了，那便是家。',
    monologue_en: 'The rain has not stopped; the umbrella stays open — you have come, and so this is home.',
    event_cn: '太和剧院 · 6 月 15 日', event_en: 'Taihe Theatre · June 15'
  },
  {
    id: 'tangbohu',
    gender: 'male',
    role_type: '文武生',
    name_cn: '唐伯虎', name_en: 'Tang Bohu',
    play_cn: '《三笑姻缘》', play_en: 'Three Smiles, One Marriage',
    traits: { '痴情': 6, '烈': 3, '飘逸': 6, '智慧': 9, '谐趣': 9, '决绝': 5 },
    quote_cn: '三笑成姻缘，一笔写江南。',
    quote_en: 'Three smiles spelled a marriage — and one brush painted the southlands.',
    letter_cn: '你和唐伯虎一样，把聪明和俏皮当成日常。但你不是浪荡——只有真在乎的事，你才肯下笨功夫。',
    letter_en: 'Like Tang Bohu, you wear cleverness and wit as everyday clothing. But you are not idle — only for the things you truly care about will you do the slow, patient work.',
    monologue_cn: '别只看我笑——我笑的人，是我认下的。',
    monologue_en: 'Do not be fooled by my smiles. The one I smile at — her, I have already chosen.',
    event_cn: '红霞剧场 · 6 月 22 日', event_en: 'Hongxia Theatre · June 22'
  },
  {
    id: 'jiangliuyun',
    gender: 'male',
    role_type: '文武生',
    name_cn: '江六云', name_en: 'Jiang Liuyun',
    play_cn: '《百花亭赠剑》', play_en: 'The Sword at Hundred-Flower Pavilion',
    traits: { '痴情': 7, '烈': 7, '飘逸': 5, '智慧': 7, '谐趣': 4, '决绝': 8 },
    quote_cn: '夜入百花亭，赠剑作姻缘。',
    quote_en: 'Into the Hundred-Flower Pavilion by night — and a gifted sword became our vow.',
    letter_cn: '你和江六云一样，胆子比常人大半步。但你的胆不是莽——它先想清楚再走，所以走出去就到。',
    letter_en: 'Like Jiang Liuyun, you have a half-step more courage than most. But your courage is not recklessness — it thinks first, then walks, and arrives.',
    monologue_cn: '我闯过来不为表演——我为见你一面。',
    monologue_en: 'I came in not for spectacle — I came to see your face once.',
    event_cn: '永光殿 · 6 月 28 日', event_en: 'Yongguang Hall · June 28'
  },
  {
    id: 'wenpingsheng',
    gender: 'male',
    role_type: '文武生',
    name_cn: '文萍生', name_en: 'Man Ping-sang',
    play_cn: '《胡不归》', play_en: 'Why Don\'t You Return',
    traits: { '痴情': 9, '烈': 6, '飘逸': 5, '智慧': 6, '谐趣': 1, '决绝': 8 },
    quote_cn: '一身戎装归来路，长歌当哭祭亡魂。',
    quote_en: 'In armor I return along the road — and my long song is the dirge for one believed dead.',
    letter_cn: '你和文萍生一样，是会被"该尽的孝"和"该爱的人"撕成两半的人。但你最后选的那一边，连你自己都不曾原谅。',
    letter_en: 'Like Man Ping-sang, you are one who can be torn between filial duty and the one you love. The side you finally chose — even you have not forgiven yourself for choosing it.',
    monologue_cn: '坟前站着的，不是英雄——是迟到的人。',
    monologue_en: 'The one standing at this grave is no hero — only one who came too late.',
    event_cn: '香江戏院 · 7 月 5 日', event_en: 'Xiangjiang Opera House · July 5'
  },

  /* === 帝王 === */
  {
    id: 'chongzhen',
    gender: 'male',
    role_type: '武生',
    name_cn: '崇祯帝', name_en: 'Emperor Chongzhen',
    play_cn: '《帝女花》', play_en: 'Princess Changping',
    traits: { '痴情': 4, '烈': 9, '飘逸': 4, '智慧': 7, '谐趣': 0, '决绝': 10 },
    quote_cn: '朕非亡国之君，臣皆亡国之臣。',
    quote_en: 'I was no emperor of a falling state — but the ministers belonged to one.',
    letter_cn: '你和崇祯一样，把责任扛到最后一刻。世界不会原谅一个最终输了的人——但你不为他们活，你为自己许过的承诺活。',
    letter_en: 'Like Chongzhen, you carry your responsibility to the very last hour. The world does not forgive one who in the end loses — but you do not live for them. You live for the promise you once made.',
    monologue_cn: '剑悬在我手——我可以选不举它，但今夜不行。',
    monologue_en: 'The sword hangs in my hand — I could choose not to raise it, but not tonight.',
    event_cn: '广府大剧院 · 5 月 18 日', event_en: 'Guangfu Grand Theatre · May 18'
  },
  {
    id: 'shunzhi',
    gender: 'male',
    role_type: '武生',
    name_cn: '清帝顺治', name_en: 'Emperor Shunzhi',
    play_cn: '《帝女花》', play_en: 'Princess Changping',
    traits: { '痴情': 5, '烈': 5, '飘逸': 6, '智慧': 9, '谐趣': 2, '决绝': 7 },
    quote_cn: '一国之主，亦是一笔账。',
    quote_en: 'A ruler of a nation is also a ledger of accounts.',
    letter_cn: '你和顺治一样，权力高位，仍能听见低处的声音。这份"听得见"，是少数当权者保留的人性。',
    letter_en: 'Like Shunzhi, even at the highest seat you can still hear voices from below. That ability to hear is the humanity few in power keep.',
    monologue_cn: '准你所求——但你也得替我准一件事。',
    monologue_en: 'I grant what you ask — but you, too, must grant me one thing.',
    event_cn: '广府大剧院 · 5 月 18 日', event_en: 'Guangfu Grand Theatre · May 18'
  },
  {
    id: 'lihouzhu',
    gender: 'male',
    role_type: '文武生',
    name_cn: '李煜', name_en: 'Li Yu (Last Emperor of Tang)',
    play_cn: '《李后主》', play_en: 'The Last Emperor of Southern Tang',
    traits: { '痴情': 8, '烈': 4, '飘逸': 10, '智慧': 7, '谐趣': 2, '决绝': 4 },
    quote_cn: '问君能有几多愁？恰似一江春水向东流。',
    quote_en: 'How much sorrow can you have? Like the river of spring waters running east, ever east.',
    letter_cn: '你和李煜一样，败给了世界，却赢了某种比胜利更长久的东西。你诗里的那个"故国"，是任何征服者都拿不走的。',
    letter_en: 'Like Li Yu, you may lose to the world yet win something longer-lasting than victory. The "homeland" in your poetry — no conqueror can take it away.',
    monologue_cn: '江山没了，词还在——这便够了。',
    monologue_en: 'The kingdom is gone; the songs remain — and that is enough.',
    event_cn: '永光殿 · 7 月 12 日', event_en: 'Yongguang Hall · July 12'
  },
  {
    id: 'tangminghuang',
    gender: 'male',
    role_type: '武生',
    name_cn: '唐明皇', name_en: 'Emperor Xuanzong',
    play_cn: '《长生殿》', play_en: 'The Palace of Eternal Life',
    traits: { '痴情': 8, '烈': 5, '飘逸': 6, '智慧': 7, '谐趣': 4, '决绝': 5 },
    quote_cn: '在天愿作比翼鸟，在地愿为连理枝。',
    quote_en: 'In heaven, may we be twin-flying birds. On earth, branches that share one root.',
    letter_cn: '你和唐明皇一样，有过权力的人。对自己有过的时刻，你比谁都清楚——那不是权力给的，是另一个人。',
    letter_en: 'Like Emperor Xuanzong, you have once held power. And you know better than anyone — those moments that mattered, were not given by power. They were given by one other person.',
    monologue_cn: '高位不重要——可以并肩看月亮的那个人才重要。',
    monologue_en: 'High position is no matter. What matters is the one who could stand beside me to watch the moon.',
    event_cn: '广府大剧院 · 6 月 12 日', event_en: 'Guangfu Grand Theatre · June 12'
  },

  /* === 大花脸 / 净 === */
  {
    id: 'baozheng',
    gender: 'male',
    role_type: '净',
    name_cn: '包拯', name_en: 'Bao Zheng',
    play_cn: '《铡美案》', play_en: 'The Justice Lord',
    traits: { '痴情': 1, '烈': 8, '飘逸': 2, '智慧': 10, '谐趣': 0, '决绝': 10 },
    quote_cn: '王子犯法，与庶民同罪。',
    quote_en: 'A prince who breaks the law shares the guilt of any common man.',
    letter_cn: '你和包拯一样，认死一个理。世故的人觉得你"轴"——可正是因为这世上还有这种"轴"的人，那些没人替的人，才有得替。',
    letter_en: 'Like Bao Zheng, you fix on one principle. The worldly call you stubborn — but it is because such people exist that those without a voice still have someone to speak for them.',
    monologue_cn: '我从不为难任何人——除非他先为难了别人。',
    monologue_en: 'I trouble no one — unless they have first troubled the helpless.',
    event_cn: '广府大剧院 · 7 月 8 日', event_en: 'Guangfu Grand Theatre · July 8'
  },
  {
    id: 'jiasidao',
    gender: 'male',
    role_type: '净',
    name_cn: '贾似道', name_en: 'Jia Sidao',
    play_cn: '《再世红梅记》', play_en: 'Reborn from the Red Plum',
    traits: { '痴情': 2, '烈': 7, '飘逸': 2, '智慧': 8, '谐趣': 3, '决绝': 8 },
    quote_cn: '权重于山，谁敢逆我？',
    quote_en: 'My power outweighs the mountains — who dares oppose me?',
    letter_cn: '你和贾似道一样，惯于让别人配合你的节奏——这本身没错，错的是把"配合"当成了"认同"。',
    letter_en: 'Like Jia Sidao, you are accustomed to others moving at your tempo. That itself is not wrong — what is wrong is mistaking compliance for agreement.',
    monologue_cn: '我赢过太多次——所以不再分得清谁怕我，谁恨我。',
    monologue_en: 'I have won too many times — and so I have lost the ability to tell who fears me from who hates me.',
    event_cn: '太和剧院 · 7 月 15 日', event_en: 'Taihe Theatre · July 15'
  },
  {
    id: 'lutaiwei',
    gender: 'male',
    role_type: '净',
    name_cn: '卢太尉', name_en: 'Marshal Lu',
    play_cn: '《紫钗记》', play_en: 'The Purple Hairpin',
    traits: { '痴情': 1, '烈': 9, '飘逸': 2, '智慧': 5, '谐趣': 1, '决绝': 8 },
    quote_cn: '一纸婚约，便是天命。',
    quote_en: 'A single marriage decree — that is heaven\'s mandate.',
    letter_cn: '你和卢太尉一样，习惯用力量解决一切。但有些事——比如别人心里的人——力量碰不到。这是你最难学的一课。',
    letter_en: 'Like Marshal Lu, you are used to solving everything by force. But some things — like the person already in another\'s heart — force cannot touch. That is your hardest lesson.',
    monologue_cn: '我下过的命令，从不缩回。可我没下过让她爱我的命令。',
    monologue_en: 'No order I have given have I withdrawn. But I never gave the order to be loved.',
    event_cn: '南国剧场 · 6 月 1 日', event_en: 'Nanguo Theatre · June 1'
  },
  {
    id: 'zhouzhong',
    gender: 'male',
    role_type: '丑生',
    name_cn: '周钟', name_en: 'Zhou Zhong',
    play_cn: '《帝女花》', play_en: 'Princess Changping',
    traits: { '痴情': 3, '烈': 3, '飘逸': 3, '智慧': 5, '谐趣': 8, '决绝': 4 },
    quote_cn: '世道乱，我先弯一弯。',
    quote_en: 'The world is broken — let me bend a little, just for now.',
    letter_cn: '你和周钟一样，是个会"看风向"的人。你不坏——只是太怕失去。看你笑得自在的人，多半没看见你回家时一个人的脸。',
    letter_en: 'Like Zhou Zhong, you are someone who reads the wind. You are not evil — only too afraid of losing. Those who see you laugh easily seldom see the face you wear when you walk home alone.',
    monologue_cn: '别看我这副笑模样——这戏里我的台词最少，但说得最重。',
    monologue_en: 'Do not be fooled by my smile — I have the fewest lines in this play, and yet they weigh the most.',
    event_cn: '广府大剧院 · 5 月 18 日', event_en: 'Guangfu Grand Theatre · May 18'
  },

  /* === 武生 / 武戏英雄 === */
  {
    id: 'guanyu',
    gender: 'male',
    role_type: '武生',
    name_cn: '关羽', name_en: 'Guan Yu',
    play_cn: '《华容道》', play_en: 'The Huarong Pass',
    traits: { '痴情': 5, '烈': 9, '飘逸': 4, '智慧': 7, '谐趣': 1, '决绝': 10 },
    quote_cn: '过五关，斩六将——一句承诺值这价。',
    quote_en: 'Through five passes — and six generals fall. One promise was worth the price.',
    letter_cn: '你和关羽一样，把"信"看得比命大。说出去的话不能改——不是因为别人记着，是因为你自己看见。',
    letter_en: 'Like Guan Yu, you take a given word as heavier than life. The words you have spoken cannot be changed — not because others remember them, but because you yourself see them.',
    monologue_cn: '一句承诺，我会替你扛到那一关。',
    monologue_en: 'A single promise — I will carry it for you, all the way to that pass.',
    event_cn: '广府大剧院 · 7 月 12 日', event_en: 'Guangfu Grand Theatre · July 12'
  },
  {
    id: 'zhaozilong',
    gender: 'male',
    role_type: '武生',
    name_cn: '赵子龙', name_en: 'Zhao Zilong',
    play_cn: '《长阪坡》', play_en: 'The Battle of Changban',
    traits: { '痴情': 5, '烈': 8, '飘逸': 5, '智慧': 7, '谐趣': 2, '决绝': 9 },
    quote_cn: '怀中阿斗一身白，万军不能挡。',
    quote_en: 'A child in my arms, my robe still white — and ten thousand cannot bar my way.',
    letter_cn: '你和赵子龙一样，是个能在乱军里把该护的人护到底的人。漂亮的不是你的招式——是你护着的那个人，从你身边走出来时的眼神。',
    letter_en: 'Like Zhao Zilong, you are one who can shelter the one needing shelter through chaos itself. What is beautiful is not your skill — it is the look in the eyes of the one you protected, walking out from behind you.',
    monologue_cn: '我没什么传奇——我只是没把怀里那个人放下来。',
    monologue_en: 'I have no legend — I only failed to put down the child in my arms.',
    event_cn: '太和剧院 · 7 月 18 日', event_en: 'Taihe Theatre · July 18'
  },
  {
    id: 'lübu',
    gender: 'male',
    role_type: '武生',
    name_cn: '吕布', name_en: 'Lü Bu',
    play_cn: '《凤仪亭》', play_en: 'Phoenix Pavilion',
    traits: { '痴情': 6, '烈': 9, '飘逸': 5, '智慧': 4, '谐趣': 2, '决绝': 5 },
    quote_cn: '人中吕布，马中赤兔——可惜心中无主。',
    quote_en: 'Lü Bu among men, Red Hare among horses — yet within: no master.',
    letter_cn: '你和吕布一样，是世间少有的"能力强但选择多"的人。能力是你的武器，可"选择"才是真正的考场——这一关你常常没及格。',
    letter_en: 'Like Lü Bu, you are one of the rare ones whose ability is great and whose choices are many. Ability is your weapon — but it is choosing that is the real test, and there you have often fallen short.',
    monologue_cn: '一杆方天画戟在手——我什么都打得过，除了我自己的犹豫。',
    monologue_en: 'The Heaven-Painted Halberd in my hand — I can defeat anything except my own hesitation.',
    event_cn: '红霞剧场 · 7 月 22 日', event_en: 'Hongxia Theatre · July 22'
  },
  {
    id: 'zhouyu',
    gender: 'male',
    role_type: '武生',
    name_cn: '周瑜', name_en: 'Zhou Yu',
    play_cn: '《三气周瑜》', play_en: 'The Thrice-Vexed Zhou Yu',
    traits: { '痴情': 5, '烈': 8, '飘逸': 7, '智慧': 9, '谐趣': 2, '决绝': 7 },
    quote_cn: '既生瑜，何生亮？',
    quote_en: 'If heaven made me — why also make him?',
    letter_cn: '你和周瑜一样，是个把自己绷得很紧的人。出色的人最难赢的不是别人——是接受"还有更出色的"。',
    letter_en: 'Like Zhou Yu, you hold yourself tight. The hardest battle for the brilliant is not against others — it is accepting that "there is one more brilliant."',
    monologue_cn: '我赢过很多场——只输给一个想法。',
    monologue_en: 'I have won many a battle — and lost only to a single thought.',
    event_cn: '南国剧场 · 7 月 18 日', event_en: 'Nanguo Theatre · July 18'
  },
  {
    id: 'luocheng',
    gender: 'male',
    role_type: '武生',
    name_cn: '罗成', name_en: 'Luo Cheng',
    play_cn: '《罗成写书》', play_en: 'Luo Cheng Writes the Final Letter',
    traits: { '痴情': 5, '烈': 7, '飘逸': 6, '智慧': 7, '谐趣': 2, '决绝': 8 },
    quote_cn: '银枪所指，万阵无名。',
    quote_en: 'Where the silver spear points — ten thousand formations are nameless.',
    letter_cn: '你和罗成一样，年纪轻轻就背得起一支队伍。早慧的人要付的代价是——你常常没人可以问。',
    letter_en: 'Like Luo Cheng, you can carry an army at a young age. The price of early genius is this: there is rarely anyone you can ask.',
    monologue_cn: '别哭——年轻人能写到这一笔，已是赢了。',
    monologue_en: 'Do not weep — for one as young to reach this final stroke is already a victory.',
    event_cn: '永光殿 · 7 月 26 日', event_en: 'Yongguang Hall · July 26'
  },
  {
    id: 'linchong',
    gender: 'male',
    role_type: '武生',
    name_cn: '林冲', name_en: 'Lin Chong',
    play_cn: '《风雪山神庙》', play_en: 'Snow at the Mountain Shrine',
    traits: { '痴情': 5, '烈': 8, '飘逸': 5, '智慧': 7, '谐趣': 2, '决绝': 9 },
    quote_cn: '雪夜上梁山，回头无寸土。',
    quote_en: 'Up Liangshan on a snowy night — and behind me, not an inch of ground.',
    letter_cn: '你和林冲一样，被一脚一脚逼到了边缘。你不愿走极端——可一旦走，就走得彻底。这世上最干净的反抗者，往往是最迟的那一个。',
    letter_en: 'Like Lin Chong, you have been pushed to the edge step by step. You did not want extremes — but once you walked, you walked through. The cleanest rebel is often the last one to rise.',
    monologue_cn: '雪太大——我看不清前路，但我知道身后没什么可回。',
    monologue_en: 'The snow falls heavy — I cannot see the road ahead, but I know there is nothing behind to return to.',
    event_cn: '香江戏院 · 8 月 1 日', event_en: 'Xiangjiang Opera House · August 1'
  },
  {
    id: 'wusong',
    gender: 'male',
    role_type: '武生',
    name_cn: '武松', name_en: 'Wu Song',
    play_cn: '《武松打虎》', play_en: 'Wu Song Slays the Tiger',
    traits: { '痴情': 4, '烈': 10, '飘逸': 3, '智慧': 5, '谐趣': 4, '决绝': 9 },
    quote_cn: '一拳打山岗，二拳打虎王。',
    quote_en: 'One blow shakes the hillside; the second strikes the tiger king.',
    letter_cn: '你和武松一样，骨子里没那么多弯弯绕。看见不对就动手，这是简单——但能保持简单到中年，是难。',
    letter_en: 'Like Wu Song, you do not have many twists in you. You see what is wrong, you act — that is simple. But staying simple into middle age — that is hard.',
    monologue_cn: '景阳冈那只老虎——其实是先扑了我的。',
    monologue_en: 'That tiger on Jingyang Ridge — truth be told, it pounced on me first.',
    event_cn: '红霞剧场 · 8 月 5 日', event_en: 'Hongxia Theatre · August 5'
  },
  {
    id: 'yangliulang',
    gender: 'male',
    role_type: '武生',
    name_cn: '杨六郎', name_en: 'Yang Liulang',
    play_cn: '《六郎罪子》', play_en: 'The Sixth Yang Punishes His Son',
    traits: { '痴情': 4, '烈': 7, '飘逸': 5, '智慧': 7, '谐趣': 2, '决绝': 9 },
    quote_cn: '军中无私情，老父也得依军规。',
    quote_en: 'In camp there is no private affection — even an old father must obey the rules.',
    letter_cn: '你和杨六郎一样，是被"位置"框住的人。位置不是束缚——你早学会在框里活得有腔调。',
    letter_en: 'Like Yang Liulang, you are framed by your position. The frame is not a cage — you long ago learned to live within it with style.',
    monologue_cn: '今夜动手的不是父亲——是营里的将军。',
    monologue_en: 'The one who acts tonight is not the father — it is the general in this camp.',
    event_cn: '太和剧院 · 8 月 8 日', event_en: 'Taihe Theatre · August 8'
  },

  /* === 老生 / 智者 === */
  {
    id: 'kouzhun',
    gender: 'male',
    role_type: '老生',
    name_cn: '寇准', name_en: 'Kou Zhun',
    play_cn: '《调寇审潘》', play_en: 'Kou Zhun Tries Pan',
    traits: { '痴情': 3, '烈': 6, '飘逸': 4, '智慧': 9, '谐趣': 4, '决绝': 9 },
    quote_cn: '一笏在手，八面不弯。',
    quote_en: 'A tablet in my hand — and on every side I do not bend.',
    letter_cn: '你和寇准一样，是会在朝堂上把皇帝顶回去的人。这种"顶"不是莽——是因为你比他想得远。',
    letter_en: 'Like Kou Zhun, you are one who can push back at the emperor across the court. Your push is not recklessness — it is because you have thought further than he has.',
    monologue_cn: '今日我说的话——明日你会感谢。',
    monologue_en: 'What I say today — tomorrow you will be grateful for.',
    event_cn: '广府大剧院 · 8 月 12 日', event_en: 'Guangfu Grand Theatre · August 12'
  },
  {
    id: 'xiebao',
    gender: 'male',
    role_type: '老生',
    name_cn: '谢宝', name_en: 'Xie Bao',
    play_cn: '《搜书院》', play_en: 'Searching the Academy',
    traits: { '痴情': 4, '烈': 5, '飘逸': 5, '智慧': 9, '谐趣': 5, '决绝': 8 },
    quote_cn: '书院之中，王法亦敬一分。',
    quote_en: 'Within these walls, even the king\'s law shows respect.',
    letter_cn: '你和谢宝一样，懂得在大局里给小人物留一席之地。仗义不一定是惊天动地——常常只是关键时刻不让出那把椅子。',
    letter_en: 'Like Xie Bao, you know how to keep a seat for the small one within the great picture. Righteousness need not be earth-shaking — often it is just refusing, at the right moment, to give up that chair.',
    monologue_cn: '我这书院——不大，但容得下一个人。',
    monologue_en: 'My academy is not large — but it has room for one.',
    event_cn: '南国剧场 · 8 月 16 日', event_en: 'Nanguo Theatre · August 16'
  },
  {
    id: 'guanhanqing',
    gender: 'male',
    role_type: '文武生',
    name_cn: '关汉卿', name_en: 'Guan Hanqing',
    play_cn: '《关汉卿》', play_en: 'Guan Hanqing',
    traits: { '痴情': 7, '烈': 7, '飘逸': 6, '智慧': 9, '谐趣': 4, '决绝': 9 },
    quote_cn: '我是一颗蒸不烂、煮不熟的铜豌豆。',
    quote_en: 'I am a copper pea — neither steamed soft nor boiled tender.',
    letter_cn: '你和关汉卿一样，写的不是给当世人的字——你写给的，是几百年后某一个翻开它的人。',
    letter_en: 'Like Guan Hanqing, what you write is not for your contemporaries. You write for someone who will open the page hundreds of years from now.',
    monologue_cn: '这一支笔下不去——有一些事，得有人替它说一句。',
    monologue_en: 'This brush will not be put down — some things must have someone to speak them.',
    event_cn: '永光殿 · 8 月 20 日', event_en: 'Yongguang Hall · August 20'
  },
  {
    id: 'guoai',
    gender: 'male',
    role_type: '小生',
    name_cn: '郭暧', name_en: 'Guo Ai',
    play_cn: '《醉打金枝》', play_en: 'Drunken Beating of the Princess',
    traits: { '痴情': 5, '烈': 7, '飘逸': 4, '智慧': 5, '谐趣': 7, '决绝': 5 },
    quote_cn: '天家公主又如何？我家妻子先是我的。',
    quote_en: 'A princess of the imperial line — yet first, she is my wife.',
    letter_cn: '你和郭暧一样，喝多的时候才说真心话。这不算缺点——很多重要的事情，清醒着说不出口。',
    letter_en: 'Like Guo Ai, only when you have had too much do you speak the truth. It is not a flaw — too many important things will not come out sober.',
    monologue_cn: '酒醒了人也醒了——但说出去的话不收。',
    monologue_en: 'Wine clears, the head clears — but words spoken stand.',
    event_cn: '香江戏院 · 8 月 24 日', event_en: 'Xiangjiang Opera House · August 24'
  },
  {
    id: 'huangshanke',
    gender: 'male',
    role_type: '武生',
    name_cn: '黄衫客', name_en: 'The Yellow-Robed Knight',
    play_cn: '《紫钗记》', play_en: 'The Purple Hairpin',
    traits: { '痴情': 4, '烈': 6, '飘逸': 7, '智慧': 8, '谐趣': 3, '决绝': 9 },
    quote_cn: '该出手时——天下何人能拦？',
    quote_en: 'When the moment to act has come — who in this world can bar my way?',
    letter_cn: '你和黄衫客一样，平时低调，但关键时刻一出现就改写局面。世上少有"该出手时绝不犹豫"的人——你是其中一个。',
    letter_en: 'Like the Yellow-Robed Knight, you keep low until the moment arrives — and when you appear, the situation changes. Few in the world act without hesitation when the time comes — you are one.',
    monologue_cn: '你不必谢我——我管的是义，不是人。',
    monologue_en: 'You need not thank me — I served righteousness, not a person.',
    event_cn: '南国剧场 · 6 月 1 日', event_en: 'Nanguo Theatre · June 1'
  },

  /* ============================================ */
  /* ===          女角 · FEMALE (30)          === */
  /* ============================================ */

  /* === 唐涤生四大名剧 女主 === */
  {
    id: 'changping',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '长平公主', name_en: 'Princess Changping',
    play_cn: '《帝女花》', play_en: 'Princess Changping',
    traits: { '痴情': 9, '烈': 6, '飘逸': 8, '智慧': 7, '谐趣': 1, '决绝': 9 },
    quote_cn: '落花满天蔽月光，借一杯附荐凤台上。',
    quote_en: 'Falling petals veil the moon — let one cup be poured upon the phoenix terrace.',
    letter_cn: '你和长平公主一样，把一段感情当成最后一件大事来办。哪怕天倾地覆，那一句"我愿意"，你也照样说出口。',
    letter_en: 'Like Princess Changping, you treat one love as the final great matter. Even when the heavens fall, you will still speak that single word — yes.',
    monologue_cn: '这一夜，是我最后的一身红衣——你来得正好。',
    monologue_en: 'This night, this is my final red garment — you came at the right hour.',
    event_cn: '广府大剧院 · 5 月 18 日', event_en: 'Guangfu Grand Theatre · May 18'
  },
  {
    id: 'huoxiaoyu',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '霍小玉', name_en: 'Huo Xiaoyu',
    play_cn: '《紫钗记》', play_en: 'The Purple Hairpin',
    traits: { '痴情': 10, '烈': 7, '飘逸': 6, '智慧': 6, '谐趣': 1, '决绝': 7 },
    quote_cn: '紫玉钗头春欲老。',
    quote_en: 'Upon the purple hairpin, the spring grows old.',
    letter_cn: '你和霍小玉一样，把"被在乎"当成命。她那一支紫钗、那场雨里的等待，都是她替每个深情的人交出的注脚。',
    letter_en: 'Like Huo Xiaoyu, you take "being cherished" as your very life. Her purple hairpin, her waiting in the rain — these are footnotes she offers for every deeply-loving soul.',
    monologue_cn: '我没什么大愿——只想被记得。',
    monologue_en: 'I ask for no great wish — only to be remembered.',
    event_cn: '南国剧场 · 6 月 1 日', event_en: 'Nanguo Theatre · June 1'
  },
  {
    id: 'duliniang',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '杜丽娘', name_en: 'Du Liniang',
    play_cn: '《牡丹亭惊梦》', play_en: 'The Peony Pavilion',
    traits: { '痴情': 10, '烈': 2, '飘逸': 9, '智慧': 6, '谐趣': 1, '决绝': 4 },
    quote_cn: '情不知所起，一往而深。',
    quote_en: 'Love arises from nowhere — yet runs to the very depth.',
    letter_cn: '你和杜丽娘一样，会为一场梦动心思，会为没见过的人，先伤心起来。她在四百年前替你说过这些话，现在轮到你听她说一次。',
    letter_en: 'Like Du Liniang, you would lose yourself in a dream and grieve for someone you have never met. Four centuries ago she spoke these words for you. Tonight, listen — she speaks them again.',
    monologue_cn: '你来了。我等了你很久——比这场梦还要久。',
    monologue_en: 'So you came. I have waited a long time — longer than this dream.',
    event_cn: '广府大剧院 · 5 月 30 日', event_en: 'Guangfu Grand Theatre · May 30'
  },
  {
    id: 'lihuiniang',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '李慧娘', name_en: 'Li Huiniang',
    play_cn: '《再世红梅记》', play_en: 'Reborn from the Red Plum',
    traits: { '痴情': 7, '烈': 10, '飘逸': 5, '智慧': 6, '谐趣': 1, '决绝': 9 },
    quote_cn: '红梅落雪，幽魂归来。',
    quote_en: 'Red plum upon the snow — the ghost returns.',
    letter_cn: '你和李慧娘一样，胸中有火，从不忍气吞声。被亏欠了，你不会假装没事。她替你穿过生死的门，把一句"不甘心"喊出来。',
    letter_en: 'Like Li Huiniang, you carry fire and never swallow your wounds. Wronged, you never pretend otherwise. She walks through death itself — to give voice to that single word: refused.',
    monologue_cn: '我从那场雪里走回来——只为一句没说完的话。',
    monologue_en: 'I have walked back through that snow — to finish one unfinished word.',
    event_cn: '广府大剧院 · 5 月 25 日', event_en: 'Guangfu Grand Theatre · May 25'
  },
  {
    id: 'luzhaorong',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '卢昭容', name_en: 'Lu Zhaorong',
    play_cn: '《再世红梅记》', play_en: 'Reborn from the Red Plum',
    traits: { '痴情': 8, '烈': 4, '飘逸': 7, '智慧': 6, '谐趣': 4, '决绝': 5 },
    quote_cn: '镜里红颜，原是别人。',
    quote_en: 'The face in the mirror — was, all along, someone else.',
    letter_cn: '你和卢昭容一样，和某个不该认识的人长得有点像。"巧合"是这个世界给认真的人的奖品——你担得起这个巧合。',
    letter_en: 'Like Lu Zhaorong, you bear a likeness to someone you should not know. A coincidence is the world\'s gift to those who take things seriously — you can carry this one.',
    monologue_cn: '别人说我是她——我说不必。我是我，但我懂她。',
    monologue_en: 'They say I am her — I say no need. I am myself, but I understand her.',
    event_cn: '广府大剧院 · 5 月 25 日', event_en: 'Guangfu Grand Theatre · May 25'
  },

  /* === 其他经典剧目 女主 === */
  {
    id: 'xiesuqiu',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '谢素秋', name_en: 'Xie Suqiu',
    play_cn: '《蝶影红梨记》', play_en: 'Butterfly and Red Pear Blossom',
    traits: { '痴情': 8, '烈': 5, '飘逸': 9, '智慧': 9, '谐趣': 3, '决绝': 6 },
    quote_cn: '蝶影双双红梨下。',
    quote_en: 'Butterfly shadows — two of them — beneath the red pear.',
    letter_cn: '你和谢素秋一样，懂得用聪明保护温柔。在该张扬时含蓄，在该决断时微笑。世人误读你，那是他们的事。',
    letter_en: 'Like Xie Suqiu, you know how to use cleverness to protect tenderness. You are subtle when others are loud, and you smile when you decide. The world misreads you — but that is its problem.',
    monologue_cn: '蝶影成双，从来不必说出口。',
    monologue_en: 'A pair of butterfly-shadows — never needs to be spoken aloud.',
    event_cn: '南国剧场 · 6 月 8 日', event_en: 'Nanguo Theatre · June 8'
  },
  {
    id: 'wangruilan',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '王瑞兰', name_en: 'Wang Ruilan',
    play_cn: '《双仙拜月亭》', play_en: 'Two Immortals at the Moon Altar',
    traits: { '痴情': 8, '烈': 4, '飘逸': 6, '智慧': 7, '谐趣': 3, '决绝': 7 },
    quote_cn: '风雨同伞，月下成双。',
    quote_en: 'One umbrella in the rain — and beneath the moon, we became two.',
    letter_cn: '你和王瑞兰一样，知道一个共撑的伞比一座大房子值钱。乱中有定，是你最稀罕的天赋。',
    letter_en: 'Like Wang Ruilan, you know one shared umbrella is worth more than a great house. Steady amid chaos — that is your rarest gift.',
    monologue_cn: '雨没停——但有伞，便能走完。',
    monologue_en: 'The rain has not stopped — but with one umbrella, we can still finish the road.',
    event_cn: '太和剧院 · 6 月 15 日', event_en: 'Taihe Theatre · June 15'
  },
  {
    id: 'qiuxiang',
    gender: 'female',
    role_type: '二帮花旦',
    name_cn: '秋香', name_en: 'Qiu Xiang',
    play_cn: '《三笑姻缘》', play_en: 'Three Smiles, One Marriage',
    traits: { '痴情': 5, '烈': 4, '飘逸': 4, '智慧': 8, '谐趣': 9, '决绝': 5 },
    quote_cn: '一笑如花，三笑成缘。',
    quote_en: 'One smile like a flower; three smiles, a fated bond.',
    letter_cn: '你和秋香一样，看破世情但不愤世。三个微笑你给得很谨慎——不是什么人都值得你那一笑。',
    letter_en: 'Like Qiu Xiang, you see the world clearly without being bitter. Your three smiles you give carefully — not everyone deserves one.',
    monologue_cn: '别人看我笑——我也在看是谁笑得最真。',
    monologue_en: 'Others see me smile — but I am watching to see whose smile is the most honest.',
    event_cn: '红霞剧场 · 6 月 22 日', event_en: 'Hongxia Theatre · June 22'
  },
  {
    id: 'baihuagongzhu',
    gender: 'female',
    role_type: '刀马旦',
    name_cn: '百花公主', name_en: 'Princess Baihua',
    play_cn: '《百花亭赠剑》', play_en: 'The Sword at Hundred-Flower Pavilion',
    traits: { '痴情': 6, '烈': 8, '飘逸': 5, '智慧': 7, '谐趣': 4, '决绝': 9 },
    quote_cn: '一剑相赠，便是终身。',
    quote_en: 'One sword bestowed — that is a vow for a lifetime.',
    letter_cn: '你和百花公主一样，喜欢就喜欢，不喜欢就不喜欢，剑都赠了还有什么不好说的。这种利落，是天底下最稀缺的礼物。',
    letter_en: 'Like Princess Baihua, your "yes" is yes and your "no" is no — once a sword is given, what is left to be unsaid? Such directness is the rarest gift in the world.',
    monologue_cn: '我送的不是剑——是一句话：从此你算我的人。',
    monologue_en: 'I did not give you a sword — I gave you a sentence: from now, you are mine.',
    event_cn: '永光殿 · 6 月 28 日', event_en: 'Yongguang Hall · June 28'
  },
  {
    id: 'zhaopinniang',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '赵颦娘', name_en: 'Zhao Pin-niang',
    play_cn: '《胡不归》', play_en: 'Why Don\'t You Return',
    traits: { '痴情': 9, '烈': 4, '飘逸': 6, '智慧': 6, '谐趣': 1, '决绝': 6 },
    quote_cn: '胡不归——一句问，够我想一生。',
    quote_en: '"Why have you not returned?" — this single question is enough for one life.',
    letter_cn: '你和赵颦娘一样，能在病中不抱怨，在被误会时不解释。她的安静不是软弱——是她已经替这事担了一切。',
    letter_en: 'Like Zhao Pin-niang, you can be ill without complaint, misjudged without defending yourself. Her quiet is not weakness — it is because she has already borne it all alone.',
    monologue_cn: '回来了？——那便好。坐一坐，坐一坐就够。',
    monologue_en: 'You have returned? — then it is well. Sit a while. To sit a while is enough.',
    event_cn: '香江戏院 · 7 月 5 日', event_en: 'Xiangjiang Opera House · July 5'
  },

  /* === 帝王后妃 / 公主 === */
  {
    id: 'yangguifei',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '杨贵妃', name_en: 'Yang Guifei',
    play_cn: '《长生殿》', play_en: 'The Palace of Eternal Life',
    traits: { '痴情': 9, '烈': 6, '飘逸': 8, '智慧': 5, '谐趣': 5, '决绝': 6 },
    quote_cn: '七月七日长生殿，夜半无人私语时。',
    quote_en: 'On the seventh of the seventh, in the Palace of Eternal Life — at midnight, when none could overhear, we spoke.',
    letter_cn: '你和杨贵妃一样，活得明亮、爱得明亮、连忧愁也是明亮的。世人爱你的明亮，但他们少有人耐心看你怎么暗下去。',
    letter_en: 'Like Yang Guifei, you live brightly, love brightly — even your sorrows are bright. The world loves your light, but few have the patience to see how it dims.',
    monologue_cn: '马嵬坡的事我已经走过了——你不必再问。',
    monologue_en: 'Mawei Slope is behind me. You need not ask of it again.',
    event_cn: '广府大剧院 · 6 月 12 日', event_en: 'Guangfu Grand Theatre · June 12'
  },
  {
    id: 'wangzhaojun',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '王昭君', name_en: 'Wang Zhaojun',
    play_cn: '《昭君出塞》', play_en: 'Zhaojun Leaves the Pass',
    traits: { '痴情': 6, '烈': 5, '飘逸': 8, '智慧': 7, '谐趣': 1, '决绝': 8 },
    quote_cn: '一支琵琶过塞外，回首千山万山。',
    quote_en: 'One pipa carried beyond the frontier — and looking back, mountain upon mountain.',
    letter_cn: '你和王昭君一样，会替别人担起一段没人愿意担的路。她背着一支琵琶走过塞外，背的不是怨——是一个国家的体面。',
    letter_en: 'Like Wang Zhaojun, you can shoulder a road no one else will walk. She carried a pipa across the frontier, and what she carried was not bitterness — but the dignity of a nation.',
    monologue_cn: '塞风起了——这一程，我自己走得完。',
    monologue_en: 'The frontier wind has risen — this road, I will walk to its end alone.',
    event_cn: '太和剧院 · 7 月 12 日', event_en: 'Taihe Theatre · July 12'
  },
  {
    id: 'hongluan',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '红鸾郡主', name_en: 'Princess Hongluan',
    play_cn: '《凤阁恩仇未了情》', play_en: 'Phoenix Pavilion: Unfinished',
    traits: { '痴情': 7, '烈': 6, '飘逸': 5, '智慧': 9, '谐趣': 6, '决绝': 8 },
    quote_cn: '凤阁之上，男装亦堂堂。',
    quote_en: 'Atop the phoenix tower — even in a man\'s robes I stand tall.',
    letter_cn: '你和红鸾郡主一样，能换上不属于自己的身份去办成一件事。这种"演得像"——不是欺骗，是一种你比身份本身更大的能力。',
    letter_en: 'Like Princess Hongluan, you can wear a borrowed identity to accomplish a task. The skill is not deception — it is that you are larger than the identity itself.',
    monologue_cn: '换一身衣裳是容易的——难的是换回来时还认得自己。',
    monologue_en: 'To change one\'s clothes is easy — what is hard is recognizing oneself when changing back.',
    event_cn: '南国剧场 · 7 月 20 日', event_en: 'Nanguo Theatre · July 20'
  },
  {
    id: 'shengping',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '升平公主', name_en: 'Princess Shengping',
    play_cn: '《醉打金枝》', play_en: 'Drunken Beating of the Princess',
    traits: { '痴情': 6, '烈': 7, '飘逸': 5, '智慧': 6, '谐趣': 6, '决绝': 5 },
    quote_cn: '驸马手重——倒是教我学了点本事。',
    quote_en: 'The prince-consort\'s hand was heavy — yet from it I learned a thing.',
    letter_cn: '你和升平公主一样，被宠坏过，但还能被打醒。能被打醒，是好事——宠坏了一辈子的人是没救的。',
    letter_en: 'Like Princess Shengping, you have been spoiled — but you can still be sobered. To be sobered is a good thing — those spoiled forever cannot be saved.',
    monologue_cn: '今晚的事——明日不必传出去。',
    monologue_en: 'What happened tonight — let it not be told tomorrow.',
    event_cn: '香江戏院 · 8 月 24 日', event_en: 'Xiangjiang Opera House · August 24'
  },

  /* === 武旦 / 巾帼 === */
  {
    id: 'muguiying',
    gender: 'female',
    role_type: '刀马旦',
    name_cn: '穆桂英', name_en: 'Mu Guiying',
    play_cn: '《穆桂英挂帅》', play_en: 'Mu Guiying Takes Command',
    traits: { '痴情': 5, '烈': 9, '飘逸': 5, '智慧': 8, '谐趣': 4, '决绝': 10 },
    quote_cn: '五十三岁挂帅，老身一笑出征。',
    quote_en: 'At fifty-three I take the command — this old woman rides out smiling.',
    letter_cn: '你和穆桂英一样，年纪渐长却越来越敢。不再是少女的猛——是中年才有的"我担得起"的稳。',
    letter_en: 'Like Mu Guiying, age makes you bolder, not gentler. No longer the recklessness of youth — but the middle-aged steadiness that says "I can carry this."',
    monologue_cn: '别拦我——再不出征，我就老了。',
    monologue_en: 'Do not bar my way — if I do not ride out now, I shall grow old.',
    event_cn: '广府大剧院 · 7 月 1 日', event_en: 'Guangfu Grand Theatre · July 1'
  },
  {
    id: 'fanlihua',
    gender: 'female',
    role_type: '刀马旦',
    name_cn: '樊梨花', name_en: 'Fan Lihua',
    play_cn: '《三休樊梨花》', play_en: 'Fan Lihua Thrice Divorced',
    traits: { '痴情': 7, '烈': 8, '飘逸': 7, '智慧': 7, '谐趣': 3, '决绝': 9 },
    quote_cn: '一面镜，一双剑，一身担。',
    quote_en: 'One mirror, twin swords, and on her shoulders, all of it.',
    letter_cn: '你和樊梨花一样，被休过，被疑过，但你不记仇——只记规矩。被人辜负过的强者，从不再为辜负的人留位置。',
    letter_en: 'Like Fan Lihua, you have been cast aside and doubted — yet you keep no grudge, only standards. The strong who have been wronged simply leave no seat for those who wronged them.',
    monologue_cn: '休不休我，是你的事——值不值我，是我的事。',
    monologue_en: 'To divorce me is your matter — whether you are worth me, is mine.',
    event_cn: '太和剧院 · 7 月 25 日', event_en: 'Taihe Theatre · July 25'
  },
  {
    id: 'shetaijun',
    gender: 'female',
    role_type: '老旦',
    name_cn: '佘太君', name_en: 'Madam She',
    play_cn: '《杨门女将》', play_en: 'Women Generals of the Yang',
    traits: { '痴情': 6, '烈': 8, '飘逸': 5, '智慧': 9, '谐趣': 3, '决绝': 10 },
    quote_cn: '一门忠烈，老身亲自挂帅。',
    quote_en: 'A house of loyalty — this old woman herself shall ride at its head.',
    letter_cn: '你和佘太君一样，年纪不是用来变软的——是用来积成一座山。这座山别人爬不上来，但凡你站着，就护着一群人。',
    letter_en: 'Like Madam She, you do not let years soften you — they pile up into a mountain. Others cannot scale this mountain, but as long as you stand, you shelter many.',
    monologue_cn: '七十岁该坐着——可你看，我还是站着的。',
    monologue_en: 'At seventy I should be sitting — and yet, look: I am still standing.',
    event_cn: '广府大剧院 · 7 月 1 日', event_en: 'Guangfu Grand Theatre · July 1'
  },
  {
    id: 'baisuzhen',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '白素贞', name_en: 'Bai Suzhen',
    play_cn: '《白蛇传·情》', play_en: 'Legend of the White Snake',
    traits: { '痴情': 9, '烈': 8, '飘逸': 8, '智慧': 9, '谐趣': 2, '决绝': 9 },
    quote_cn: '千年修炼，只为这一场凡间。',
    quote_en: 'A thousand years of cultivation — for this single mortal life.',
    letter_cn: '你和白素贞一样，所有的智慧、修为、力量，都肯为一个人放下。但放下不是软弱——必要时你也会断桥之上，让天地都听见。',
    letter_en: 'Like Bai Suzhen, all your wisdom, all your power, you would set aside for one person. But setting aside is not weakness — when needed, you stand on the broken bridge and let heaven and earth hear you.',
    monologue_cn: '我不是来求情的——我来履约。',
    monologue_en: 'I have not come to plead — I have come to keep my word.',
    event_cn: '广府大剧院 · 6 月 5 日', event_en: 'Guangfu Grand Theatre · June 5'
  },

  /* === 悲剧女主 / 红派经典 === */
  {
    id: 'jiaoguiying',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '焦桂英', name_en: 'Jiao Guiying',
    play_cn: '《焚香记》', play_en: 'Burning the Incense',
    traits: { '痴情': 10, '烈': 9, '飘逸': 6, '智慧': 6, '谐趣': 1, '决绝': 9 },
    quote_cn: '一炉香尽，魂归来打神。',
    quote_en: 'One censer burned to ash — and her ghost returns to strike the gods.',
    letter_cn: '你和焦桂英一样，吃过亏的人。但她吃了亏没忍着——她到神面前去问，问到神都不敢答。',
    letter_en: 'Like Jiao Guiying, you have been wronged. But she did not swallow it — she went before the gods to ask, and asked until the gods themselves dared not answer.',
    monologue_cn: '神也好，鬼也好——我今夜要一个答复。',
    monologue_en: 'God or ghost — tonight I must have an answer.',
    event_cn: '南国剧场 · 8 月 1 日', event_en: 'Nanguo Theatre · August 1'
  },
  {
    id: 'qinxianglian',
    gender: 'female',
    role_type: '青衣',
    name_cn: '秦香莲', name_en: 'Qin Xianglian',
    play_cn: '《铡美案》', play_en: 'The Justice Lord',
    traits: { '痴情': 8, '烈': 7, '飘逸': 4, '智慧': 6, '谐趣': 1, '决绝': 10 },
    quote_cn: '千里寻夫，只问一个公道。',
    quote_en: 'A thousand li to find a husband — and to ask for nothing but justice.',
    letter_cn: '你和秦香莲一样，是会带着两个孩子走完一段不该自己走的路。世上多的是嘴上要公道的人——你是其中真去走的。',
    letter_en: 'Like Qin Xianglian, you are one who can walk a road you should not have had to walk, with children in tow. The world is full of those who speak of justice — you are among the few who go.',
    monologue_cn: '我不要别的——我要他亲口回答这句。',
    monologue_en: 'I want nothing else — only that he answer this with his own mouth.',
    event_cn: '广府大剧院 · 7 月 8 日', event_en: 'Guangfu Grand Theatre · July 8'
  },
  {
    id: 'zhulianxiu',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '朱帘秀', name_en: 'Zhu Lianxiu',
    play_cn: '《关汉卿》', play_en: 'Guan Hanqing',
    traits: { '痴情': 9, '烈': 8, '飘逸': 7, '智慧': 8, '谐趣': 4, '决绝': 9 },
    quote_cn: '蝶双飞——你写一句，我便活一句。',
    quote_en: 'Two butterflies in flight — for each line you write, I live another line.',
    letter_cn: '你和朱帘秀一样，是个把"懂得"换成行动的人。她不只听他写——她把那些字活了出来，连入狱也活给他看。',
    letter_en: 'Like Zhu Lianxiu, you turn "understanding" into action. She did not merely listen to his writing — she lived those words, into prison itself, where he could see her live them.',
    monologue_cn: '别问我冷不冷——我是来陪那一支笔的。',
    monologue_en: 'Do not ask if I am cold — I have come to be with that brush.',
    event_cn: '永光殿 · 8 月 20 日', event_en: 'Yongguang Hall · August 20'
  },
  {
    id: 'doue',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '窦娥', name_en: 'Dou E',
    play_cn: '《窦娥冤》', play_en: 'Snow in Midsummer',
    traits: { '痴情': 5, '烈': 9, '飘逸': 5, '智慧': 6, '谐趣': 1, '决绝': 10 },
    quote_cn: '六月飞雪，天地为我作证。',
    quote_en: 'Snow in the sixth month — let heaven and earth bear witness.',
    letter_cn: '你和窦娥一样，被冤枉时不缩——她那一句"六月飞雪"是替所有沉默的人喊的。世道不见得有报应，但她让你信，至少有人替你喊过一次。',
    letter_en: 'Like Dou E, you do not shrink when wronged — her cry "snow in the sixth month" was for all the silenced. The world may have no reckoning, but she lets you believe at least once, someone cried out for you.',
    monologue_cn: '我不是要你信——我是要你听见。',
    monologue_en: 'I am not asking you to believe — only to hear.',
    event_cn: '红霞剧场 · 8 月 12 日', event_en: 'Hongxia Theatre · August 12'
  },

  /* === 灵动 / 闺秀 === */
  {
    id: 'hongniang',
    gender: 'female',
    role_type: '二帮花旦',
    name_cn: '红娘', name_en: 'Hongniang',
    play_cn: '《西厢记》', play_en: 'Romance of the Western Chamber',
    traits: { '痴情': 4, '烈': 4, '飘逸': 2, '智慧': 10, '谐趣': 9, '决绝': 6 },
    quote_cn: '世间难成的事，多半是没遇上一个红娘。',
    quote_en: 'The hardest things in life simply lacked a Hongniang.',
    letter_cn: '你和红娘一样，看得明白、说得机灵、办得妥帖。别人的难处你三言两语就拨云见日。但你的好——你常常自己不说。',
    letter_en: 'Like Hongniang, you see clearly, speak cleverly, resolve gracefully. You untangle others knot by knot. But your own kindness — you so often leave unspoken.',
    monologue_cn: '说一句吧——你已经撮合了那么多人了。这一回，谁来撮合你？',
    monologue_en: 'Speak — you have brought so many together. Now: who will speak for you?',
    event_cn: '南国剧场 · 5 月 20 日', event_en: 'Nanguo Theatre · May 20'
  },
  {
    id: 'cuiyingying',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '崔莺莺', name_en: 'Cui Yingying',
    play_cn: '《西厢记》', play_en: 'Romance of the Western Chamber',
    traits: { '痴情': 9, '烈': 3, '飘逸': 7, '智慧': 8, '谐趣': 2, '决绝': 5 },
    quote_cn: '待月西厢下，迎风户半开。',
    quote_en: 'Awaiting the moon by the western chamber — the door, half-open to the breeze.',
    letter_cn: '你和崔莺莺一样，外表克制，心里却惊涛骇浪。把秘密藏得好不是冷漠——是因为那秘密太珍贵了。',
    letter_en: 'Like Cui Yingying, you appear restrained while waves crash within. Keeping a secret well is not coldness — it is because the secret is too precious to risk.',
    monologue_cn: '门开了一半——剩下的一半，是给你自己来推的。',
    monologue_en: 'The door is half-open — the other half is yours to push.',
    event_cn: '南国剧场 · 5 月 20 日', event_en: 'Nanguo Theatre · May 20'
  },
  {
    id: 'cuilian',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '翠莲', name_en: 'Cuilian',
    play_cn: '《搜书院》', play_en: 'Searching the Academy',
    traits: { '痴情': 5, '烈': 8, '飘逸': 4, '智慧': 7, '谐趣': 5, '决绝': 8 },
    quote_cn: '我不愿做妾——我愿做我。',
    quote_en: 'I will not be a concubine — I will be myself.',
    letter_cn: '你和翠莲一样，宁可冒大险，也不愿走人安排好的路。她那个跑——是这个世界里少有的、清白的"不合作"。',
    letter_en: 'Like Cuilian, you would rather face great danger than walk a path others arranged. Her flight — was one of the world\'s rare clean refusals to comply.',
    monologue_cn: '我跑不快，但我跑得直——这就够了。',
    monologue_en: 'I cannot run fast, but I run straight — and that is enough.',
    event_cn: '南国剧场 · 8 月 16 日', event_en: 'Nanguo Theatre · August 16'
  },

  /* === 喜剧 / 老旦 === */
  {
    id: 'laoguopo',
    gender: 'female',
    role_type: '彩旦',
    name_cn: '老姑婆', name_en: 'The Spinster Aunt',
    play_cn: '《三笑姻缘》', play_en: 'Three Smiles, One Marriage',
    traits: { '痴情': 4, '烈': 4, '飘逸': 2, '智慧': 6, '谐趣': 10, '决绝': 5 },
    quote_cn: '老姑婆我也曾年轻过——可惜没人信。',
    quote_en: 'This old aunt was once young — but alas, no one will believe me.',
    letter_cn: '你和老姑婆一样，能把别人看不上的位置活成精彩。年纪、外貌、身份——你不在意；可一桌饭吃得乐不乐呵——你最在意。',
    letter_en: 'Like the Spinster Aunt, you can turn into a spectacle the role others look down on. Age, looks, status — you do not care; but whether the meal at table is merry — that, you do.',
    monologue_cn: '别低头——抬起头来，咱们这场子热闹着呢。',
    monologue_en: 'Do not lower your head — lift it up, our scene is lively yet.',
    event_cn: '红霞剧场 · 6 月 22 日', event_en: 'Hongxia Theatre · June 22'
  },
  {
    id: 'caipo',
    gender: 'female',
    role_type: '老旦',
    name_cn: '蔡婆', name_en: 'Mother Cai',
    play_cn: '《窦娥冤》', play_en: 'Snow in Midsummer',
    traits: { '痴情': 6, '烈': 3, '飘逸': 4, '智慧': 5, '谐趣': 3, '决绝': 4 },
    quote_cn: '我老了——给不了什么，只想护着这一个。',
    quote_en: 'I am old now — I have little to give, only this one to guard.',
    letter_cn: '你和蔡婆一样，没什么本事却心地纯。她不是英雄——她是英雄背后那个一辈子没说"我也累"的人。',
    letter_en: 'Like Mother Cai, you have no great power yet a clean heart. She is no hero — she is the one behind the hero who never once said "I, too, am tired."',
    monologue_cn: '别说我软——我只是不会和这个世界硬拼。',
    monologue_en: 'Do not call me weak — I only never learned to fight this world hard.',
    event_cn: '红霞剧场 · 8 月 12 日', event_en: 'Hongxia Theatre · August 12'
  },
  {
    id: 'aqingsao',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '阿庆嫂', name_en: 'Sister Aqing',
    play_cn: '《沙家浜》', play_en: 'Shajiabang',
    traits: { '痴情': 4, '烈': 5, '飘逸': 4, '智慧': 10, '谐趣': 6, '决绝': 9 },
    quote_cn: '一壶茶，三句话——什么都看明白。',
    quote_en: 'A pot of tea, three sentences — and I see everything.',
    letter_cn: '你和阿庆嫂一样，看似在端茶倒水——其实在数对面那个人的呼吸。聪明不是显摆出来的；最厉害的聪明，是别人没发现你正在看他。',
    letter_en: 'Like Sister Aqing, you may seem only to be pouring tea — but in fact you are counting your opponent\'s breath. Cleverness is not displayed; the highest is when no one notices you are watching them.',
    monologue_cn: '坐下喝一杯——慢慢说，我有时间。',
    monologue_en: 'Sit, have a cup — speak slowly. I have all the time.',
    event_cn: '香江戏院 · 8 月 30 日', event_en: 'Xiangjiang Opera House · August 30'
  },

  /* === 神仙 === */
  {
    id: 'qixiannv',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '七仙女', name_en: 'The Seventh Fairy',
    play_cn: '《天仙配》', play_en: 'The Heavenly Match',
    traits: { '痴情': 9, '烈': 4, '飘逸': 10, '智慧': 6, '谐趣': 5, '决绝': 7 },
    quote_cn: '云中下凡——只为你那一笔耕。',
    quote_en: 'Down from the clouds — only for that one furrow you turned.',
    letter_cn: '你和七仙女一样，能为一个普通人下凡。这种"下"不丢人——多少天上的神，一辈子不肯下来一次。',
    letter_en: 'Like the Seventh Fairy, you can come down for an ordinary person. There is no shame in that descent — how many heavenly beings would not, in a whole life, come down even once.',
    monologue_cn: '别怕我天上来——今晚我只是个跟你坐在桥头的人。',
    monologue_en: 'Do not fear my heavenly origin — tonight, I am only one who sits with you at the bridge.',
    event_cn: '永光殿 · 8 月 16 日', event_en: 'Yongguang Hall · August 16'
  },
  {
    id: 'zhinv',
    gender: 'female',
    role_type: '正印花旦',
    name_cn: '织女', name_en: 'The Weaver Girl',
    play_cn: '《鹊桥会》', play_en: 'Meeting at the Magpie Bridge',
    traits: { '痴情': 10, '烈': 4, '飘逸': 9, '智慧': 6, '谐趣': 3, '决绝': 7 },
    quote_cn: '一年一会，桥未断，星仍在。',
    quote_en: 'Once a year we meet — the bridge unbroken, the stars still in their place.',
    letter_cn: '你和织女一样，把"一年一次"过成了一辈子。等待这件事，对她不是煎熬——是她和心爱之人共同维持的某种神圣节奏。',
    letter_en: 'Like the Weaver Girl, you make of "once a year" a whole life. Waiting, for her, is not torment — it is a sacred rhythm she keeps together with the one she loves.',
    monologue_cn: '别替我可惜——这一夜的桥，胜过你们所有不分别的日子。',
    monologue_en: 'Do not pity me — this single bridge-night surpasses all your days that never knew parting.',
    event_cn: '永光殿 · 8 月 16 日', event_en: 'Yongguang Hall · August 16'
  }

];

/* ========================================
   6 questions × 4 options
   ======================================== */
window.QUESTIONS = [
  {
    title_cn: '你今天点这杯咖啡，最像你哪一面？',
    title_en: 'This coffee — which side of you does it feel like today?',
    options: [
      { text_cn: '醇厚回甘 · 藏起来的柔情', text_en: 'Mellow & sweet · the tenderness I hide', weights: { '痴情': 2, '飘逸': 1 } },
      { text_cn: '浓烈苦涩 · 心里那把火', text_en: 'Bold & bitter · the fire inside', weights: { '烈': 2, '决绝': 1 } },
      { text_cn: '清雅花香 · 看世界的距离', text_en: 'Light & floral · my distance from the world', weights: { '飘逸': 2, '智慧': 1 } },
      { text_cn: '甜美明亮 · 对一个人的执念', text_en: 'Sweet & bright · my fixation on one person', weights: { '痴情': 2, '谐趣': 1 } }
    ]
  },
  {
    title_cn: '朋友最常这样形容你⋯⋯',
    title_en: 'Your friends most often say...',
    options: [
      { text_cn: '"你太较真了"', text_en: '"You take everything too seriously"', weights: { '决绝': 2, '烈': 1 } },
      { text_cn: '"你想得太多了"', text_en: '"You think too much"', weights: { '智慧': 2, '飘逸': 1 } },
      { text_cn: '"你这人有意思"', text_en: '"You\'re an interesting one"', weights: { '谐趣': 2, '智慧': 1 } },
      { text_cn: '"你心很软"', text_en: '"You have a soft heart"', weights: { '痴情': 2, '飘逸': 1 } }
    ]
  },
  {
    title_cn: '看到一件不公平的事，你的第一反应？',
    title_en: 'You see something unfair. What is your first move?',
    options: [
      { text_cn: '想个聪明办法绕过去', text_en: 'Find a clever way around it', weights: { '智慧': 2, '飘逸': 1 } },
      { text_cn: '立刻就要管', text_en: 'Step in right now', weights: { '烈': 2, '决绝': 2 } },
      { text_cn: '记下来，时机到了再算账', text_en: 'Note it down — settle when the time comes', weights: { '决绝': 2, '智慧': 1 } },
      { text_cn: '帮当事人转移注意力，没那么严重', text_en: 'Distract the person, lighten the moment', weights: { '谐趣': 2, '智慧': 1 } }
    ]
  },
  {
    title_cn: '雨天独自一人，你会⋯⋯',
    title_en: 'Alone on a rainy day, you would...',
    options: [
      { text_cn: '给一个人发消息', text_en: 'Message that one person', weights: { '痴情': 3 } },
      { text_cn: '看一部老电影', text_en: 'Watch an old film', weights: { '飘逸': 2, '智慧': 1 } },
      { text_cn: '叫上朋友喝一杯', text_en: 'Call a friend out for a drink', weights: { '烈': 1, '谐趣': 2 } },
      { text_cn: '关掉手机，睡', text_en: 'Turn off the phone. Sleep.', weights: { '决绝': 2, '飘逸': 1 } }
    ]
  },
  {
    title_cn: '你的"软肋"是什么？',
    title_en: 'What is your weakness?',
    options: [
      { text_cn: '一个还在心里的人', text_en: 'A person still in my heart', weights: { '痴情': 3 } },
      { text_cn: '一件还没做成的事', text_en: 'Something I have not yet done', weights: { '决绝': 2, '烈': 1 } },
      { text_cn: '看见软弱的人', text_en: 'Seeing the helpless', weights: { '智慧': 1, '痴情': 2 } },
      { text_cn: '我没有软肋', text_en: 'I do not have one', weights: { '决绝': 2, '谐趣': 1 } }
    ]
  },
  {
    title_cn: '如果今晚有一台戏在等你，你最想看哪种？',
    title_en: 'If a show were waiting for you tonight, which would you choose?',
    options: [
      { text_cn: '凄美的爱情', text_en: 'A heartbreaking love story', weights: { '痴情': 3 } },
      { text_cn: '江湖恩仇', text_en: 'Tales of vengeance', weights: { '烈': 2, '决绝': 1 } },
      { text_cn: '才子智斗', text_en: 'A battle of wits', weights: { '智慧': 2, '谐趣': 1 } },
      { text_cn: '一段不羁的人生', text_en: 'An untamed life', weights: { '飘逸': 2, '决绝': 1 } }
    ]
  }
];

/* ========================================
   UI strings (i18n)
   ======================================== */
window.STRINGS = {
  zh: {
    brand: '粤剧 · 咖啡',
    welcome_logo: '一隅回音',
    welcome_main: '測測你是哪個角色？',
    welcome_en: 'Guess which character you discover?',
    welcome_invite: '一杯之緣 ·<br>咖啡豆香 ·<br>六個問答<br><br>留給未接觸過戲曲的你<br>走進粵劇劇場時間',
    welcome_invite_en: 'This encounter<br>One Coffee One Taste<br>Six Q&amp;A<br><br>Brings you a glance of Cantonese Opera',
    start_btn: '开始',
    intro_line1: '把咖啡端在手里。',
    intro_line2: '喝一口。',
    intro_line3: '让我看看你是谁。',
    intro_continue: '开始',
    q_progress: '第 {n} 题 / 共 6 题',
    gender_label: '在我替你寻找之前',
    gender_main: '请告诉我，你是 ——',
    gender_main_en: 'Before I begin the search, tell me — you are...',
    gender_male: '男生',
    gender_male_en: 'A man',
    gender_female: '女生',
    gender_female_en: 'A woman',
    gender_note: '我会从相应的角色里为你找一位最像的。',
    gender_note_en: 'I will find you from among the characters of your gender.',
    camera_intro_label: '再看你一眼',
    camera_intro_main: '让镜头多读你一眼——把你的"神气"也带进来。',
    camera_intro_main_en: 'Let me read your countenance, just once — let your spirit speak too.',
    camera_intro_sub: '可以跳过。这一面，只用于此刻的匹配，不会保存、不会上传。',
    camera_intro_sub_en: 'You may skip. This face is used only for matching, not saved, not uploaded.',
    camera_take: '拍照',
    camera_skip: '跳过这一步',
    camera_retake: '重拍',
    camera_use: '用这张',
    camera_perm_denied: '相机权限被拒绝。可继续跳过这一步。',
    camera_perm_denied_en: 'Camera access denied. You may skip this step.',
    loading_text: '一台戏，正在为你拉开⋯⋯',
    loading_text_en: 'A play is opening — for you',
    reading_face_text: '正在读你的眼神⋯⋯',
    reading_face_text_en: 'Reading the look in your eyes...',
    result_prelude: '你的角色是 ——',
    result_from: '来自 {play}',
    result_role: '行当：{role}',
    monologue_meta: '演员对你说话',
    monologue_meta_en: 'The Player Speaks to You',
    monologue_note: '· 实际版本由真演员录制 ·',
    listen_btn: '继续',
    to_ticket: '收下你的票',
    your_card: '你的角色卡',
    ticket_brand_cn: '广府粤剧 · 礼请',
    ticket_brand_en: 'Cantonese Opera · A Letter of Invitation',
    ticket_bearer_label: '谨呈 · TO THE BEARER',
    ticket_event_label: '若你愿意来',
    ticket_event_label_en: 'If you should choose to come',
    save_image: '保存图片',
    play_again: '再玩一次',
    save_hint: '保存到相册 · 可在朋友圈、Instagram 等处分享',
    portrait_placeholder_note: '* 此为占位插画，最终版替换为真演员剧照',
    lang_zh: '中文',
    lang_en: 'English'
  },
  en: {
    brand: 'OPERA · COFFEE',
    welcome_logo: '一隅回音',
    welcome_main: 'Guess which character you discover?',
    welcome_en: '測測你是哪個角色？',
    welcome_invite: 'This encounter<br>One Coffee One Taste<br>Six Q&amp;A<br><br>Brings you a glance of Cantonese Opera',
    welcome_invite_en: '一杯之緣 ·<br>咖啡豆香 ·<br>六個問答<br><br>留給未接觸過戲曲的你<br>走進粵劇劇場時間',
    start_btn: 'Begin',
    intro_line1: 'Hold your coffee.',
    intro_line2: 'Take a sip.',
    intro_line3: 'Now — let me see who you are.',
    intro_continue: 'Continue',
    q_progress: 'Question {n} of 6',
    gender_label: 'Before I search',
    gender_main: 'Tell me, you are —',
    gender_main_en: '请告诉我，你是 ——',
    gender_male: 'A man',
    gender_male_en: '男生',
    gender_female: 'A woman',
    gender_female_en: '女生',
    gender_note: 'I will find you among the characters of your gender.',
    gender_note_en: '我会从相应的角色里为你找一位最像的。',
    camera_intro_label: 'One more look',
    camera_intro_main: 'Let the lens read you once — bring your spirit into this too.',
    camera_intro_main_en: '让镜头多读你一眼——把你的"神气"也带进来。',
    camera_intro_sub: 'You may skip. Your face is used only for this match, not saved, not uploaded.',
    camera_intro_sub_en: '可以跳过。这一面，只用于此刻的匹配，不会保存、不会上传。',
    camera_take: 'Take Photo',
    camera_skip: 'Skip this step',
    camera_retake: 'Retake',
    camera_use: 'Use this',
    camera_perm_denied: 'Camera access denied. You may skip this step.',
    camera_perm_denied_en: '相机权限被拒绝。可继续跳过这一步。',
    loading_text: 'A play is opening — for you',
    loading_text_en: '一台戏，正在为你拉开⋯⋯',
    reading_face_text: 'Reading the look in your eyes...',
    reading_face_text_en: '正在读你的眼神⋯⋯',
    result_prelude: 'Your character is —',
    result_from: 'from {play}',
    result_role: 'Role type: {role}',
    monologue_meta: 'The Player Speaks to You',
    monologue_meta_en: '演员对你说话',
    monologue_note: '· Will be recorded by the actual performer ·',
    listen_btn: 'Listen',
    to_ticket: 'Receive your invitation',
    your_card: 'Your Card',
    ticket_brand_cn: 'CANTONESE OPERA · A LETTER OF INVITATION',
    ticket_brand_en: '广府粤剧 · 礼请',
    ticket_bearer_label: 'TO THE BEARER · 谨呈',
    ticket_event_label: 'If you should choose to come',
    ticket_event_label_en: '若你愿意来',
    save_image: 'Save Image',
    play_again: 'Try Again',
    save_hint: 'Save to your album · share anywhere',
    portrait_placeholder_note: '* Placeholder illustration — final uses real stage photography',
    lang_zh: '中文',
    lang_en: 'English'
  }
};
